---
title: "RAscunho"
author: "Camily Nunes dos Santos"
date: "2024-10-24"
output: html_document
---
  
  
```{r}
url <- "https://github.com/CamilyNunes/dados-snis-mt/raw/refs/heads/main/Dados/SNIS%20-%20S%C3%A9rie%20Hist%C3%B3rica/AgregadoSNISMT(TESTE).csv"
```
  
    

  
```{r} 
url <- "https://github.com/CamilyNunes/dados-snis-mt/raw/refs/heads/main/Dados/SNIS%20-%20S%C3%A9rie%20Hist%C3%B3rica/AgregadoSNISMT.csv"
```
     

```{r}
# Remove as linhas com valores ausentes
san <- san[complete.cases(san),]
```
  
    
```{r}
# Tentar converter a coluna de tempo para numérico, removendo possíveis caracteres
san$pop_atendida_abas_agua <- as.numeric(as.character(san$pop_atendida_abas_agua))

san$índice_coleta_esgoto <- as.numeric(as.character(san$índice_coleta_esgoto))
```
  
 
```{r}
# Remove as linhas com valores ausentes
san <- san[complete.cases(san),]
```
  
      
```{r}
#teste 1 
library(dplyr)
library(tidyr)


san <- san %>%
  mutate(across(where(is.character), ~ na_if(., "NS"))) %>%  # Converte "NS" em NA apenas nas colunas de texto
  mutate(across(where(is.numeric), ~ replace_na(., 0))) %>%  # Substitui NA por 0 nas colunas numéricas
  mutate(across(where(is.character), ~ replace_na(., "0")))  # Substitui NA por "0" nas colunas de texto
```
     
    